AWSTemplateFormatVersion: "2010-09-09"
Description: ECR repo for worker web app
Resources: 
  WorkerWebAppRepo: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "worker-web-app"
Outputs:    
  WorkerWebAppArn:
    Value: !GetAtt WorkerWebAppRepo.Arn
    Export: 
      Name: WorkerWebAppArn